[package]
name = "rusty-js"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "*"

parking_lot = "*"


rusty-js-core = {version = "*", path = "../rusty-js-core"}